version: "3"

services:

  bdfr:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: bdfr
    container_name: bdfr
    ports:
      - "8080:8080"
      - "7634:7634"
    volumes:
      - .:/bdfr:z
    container_name: bdfr_container
    network_mode: bridge 
